# Generated by Django 3.1.2 on 2022-02-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grouping', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreData',
        ),
    ]
