# Generated by Django 3.1.2 on 2022-02-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedata',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
