# Generated by Django 4.0.2 on 2022-02-16 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_storedata_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedata',
            name='date',
            field=models.DateField(default=datetime.date(2022, 2, 16)),
        ),
        migrations.AlterField(
            model_name='storedata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
