# Generated by Django 4.0 on 2022-02-18 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_alter_storedata_date_alter_storedata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedata',
            name='date',
            field=models.DateField(default=datetime.date(2022, 2, 18)),
        ),
    ]
